// Turns eval/TABLE.md (generated by eval/table.py from the real eval runs) into src/data/eval.json for the Results page.
// The page shows these numbers as they are; nothing is typed by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const md = readFileSync(join(here, "..", "..", "eval", "TABLE.md"), "utf8");
const lines = md.split(/\r?\n/);

const tableLines = lines.filter((l) => l.startsWith("|"));
const cells = (l) => l.split("|").slice(1, -1).map((c) => c.trim());
const header = cells(tableLines[0]);
const rows = tableLines.slice(2).map((l) => {
  const c = cells(l);
  return { metric: c[0], values: c.slice(1) };
});

const testSetLine = lines.find((l) => l.startsWith("Generated by")) ?? "";
const questions = /Test set: (\d+) questions/.exec(testSetLine)?.[1] ?? null;
const meaning = lines.find((l) => l.startsWith("**What the numbers mean.**")) ?? "";

if (rows.length < 8 || header.length < 5) throw new Error("eval/TABLE.md did not parse: expected a metric table");

writeFileSync(
  join(here, "..", "src", "data", "eval.json"),
  JSON.stringify({ questions: questions ? Number(questions) : null, systems: header.slice(1), rows, caveat: meaning.replace("**What the numbers mean.** ", "") }, null, 2) + "\n",
);
console.log(`eval.json: ${rows.length} metrics, ${header.length - 1} systems, ${questions} questions`);
